# Generated by Django 3.2.9 on 2021-11-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=20, unique=True)),
                ('data', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
